version: '3.2'

services:
  
  wwww:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  webgrind:
    image: creativeprojects/webgrind
    ports:
      - '8090:80'
    volumes:
      - "./app/profiling:/tmp/xdebug"
